version: '3.8'
services:
  fe-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "2005:2005"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/stl/fe # Mount source code vào container để đồng bộ khi phát triển
