import { DevtoolsProvider } from '@providers/devtools';
import { useNotificationProvider } from '@refinedev/antd';
import { Refine } from '@refinedev/core';
import { RefineKbar, RefineKbarProvider } from '@refinedev/kbar';
// import routerProvider from '@refinedev/nextjs-router';
import { Metadata } from 'next';
import { cookies } from 'next/headers';
import React, { Suspense } from 'react';

import { AntdRegistry } from '@ant-design/nextjs-registry';
import { AppIcon } from '@components/app-icon';
import { ColorModeContextProvider } from '@contexts/color-mode';
// import {authProvider} from '@providers/auth-provider';
import { dataProvider } from '@providers/data-provider';
import '@refinedev/antd/dist/reset.css';
import { ConfigProvider } from 'antd';
import antdTheme from '@configs/antdTheme';
import STLIcon from "../../public/images/logo/logo-STL-02.svg"

export const metadata: Metadata = {
  title: 'STL | Booking',
  description: 'Generated by create refine app',
  icons: {
    icon: '../../public/images/logo/logo-STL-02.svg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const theme = cookieStore.get('theme');
  const defaultMode = theme?.value === 'dark' ? 'dark' : 'light';

  return (
    <html lang="en">
      <body>
        <Suspense>
          <RefineKbarProvider>
            <AntdRegistry>
              <ConfigProvider theme={antdTheme}>
                <ColorModeContextProvider defaultMode={defaultMode}>
                  {/* <DevtoolsProvider> */}
                  <Refine
                    // routerProvider={routerProvider}
                    // authProvider={authProvider}
                    dataProvider={dataProvider}
                    notificationProvider={useNotificationProvider}
                    resources={[
                      {
                        name: 'home',
                        // list: '/blog-posts',
                        // create: '/blog-posts/create',
                        // edit: '/blog-posts/edit/:id',
                        // show: '/blog-posts/show/:id',
                        // meta: {
                        //   canDelete: true,
                        // },
                      },
                      // {
                      //   name: 'blog-posts',
                      //   list: '/blog-posts',
                      //   create: '/blog-posts/create',
                      //   edit: '/blog-posts/edit/:id',
                      //   show: '/blog-posts/show/:id',
                      //   meta: {
                      //     canDelete: true,
                      //   },
                      // },
                      // {
                      //   name: 'categories',
                      //   list: '/categories',
                      //   create: '/categories/create',
                      //   edit: '/categories/edit/:id',
                      //   show: '/categories/show/:id',
                      //   meta: {
                      //     canDelete: true,
                      //   },
                      // },
                    ]}
                    options={{
                      syncWithLocation: true,
                      warnWhenUnsavedChanges: true,
                      useNewQueryKeys: true,
                      projectId: 'k3NvGV-qBcRmD-kZ9nGr',
                      title: { text: 'STL | Booking', icon: <STLIcon /> },
                    }}
                  >
                    {children}
                    <RefineKbar />
                  </Refine>
                  {/* </DevtoolsProvider> */}
                </ColorModeContextProvider>
              </ConfigProvider>
            </AntdRegistry>
          </RefineKbarProvider>
        </Suspense>
      </body>
    </html>
  );
}
